swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:

  /user/login:
    post:
  # curl -X POST "http://localhost:3001/api/v1/user/login" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"email\": \"tony@stark.com\", \"password\": \"password123\"}"
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
  # curl -X POST "http://localhost:3001/api/v1/user/profile" -H "accept: application/json" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3M2I4Y2E0OTA0YzE2MGVhNDIzNTY4NyIsImlhdCI6MTc0MjU3MDk0MywiZXhwIjoxNzQyNjU3MzQzfQ.vaWuOrTIOOp7tdkTazp5Pt8VUbNTBEd8fGj5vxZUTQ4" -d ""
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    put:
     # curl -X PUT "http://localhost:3001/api/v1/user/profile" -H "accept: application/json" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3M2I4Y2E0OTA0YzE2MGVhNDIzNTY4NyIsImlhdCI6MTc0MjU3MDk0MywiZXhwIjoxNzQyNjU3MzQzfQ.vaWuOrTIOOp7tdkTazp5Pt8VUbNTBEd8fGj5vxZUTQ4" -H "Content-Type: application/json" -d "{ \"firstName\": \"Tonyyyy\", \"lastName\": \"Starkkkk\"}"
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /accounts:
    post:
      security:
        - Bearer: []
      tags:
        - User accounts
      summary: All user accounts
      description: Get all the user accounts
      # operationId: getAccounts
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: userId
          in: path
          description: Attach User ID
          required: true
          type: string
      produces:
        - application/json    
      responses:
        '200':
          description: User accounts retrieved successully
          schema:
            items:
              $ref: '#/definitions/UserAccounts'
        '404':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /transactions/{accountId}:
    post:
      security:
        - Bearer: []
      tags:
        - User transactions
      summary: All transactions
      description: Get all user transactions of an account
      # operationId: getTransactionByAccountId
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: Attach account Id 
          required: true
          type: string
      produces:
       - application/json  
      responses:
        '200':
          description: Transactions retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '404':
          description: Invalid fields
        '500':
          description: Internal Server Error

  /transactions/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - User transaction category
      summary: Update category
      description: Update a transaction category
      # operationId: updateCategory
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: Attach Id transaction
          required: true
          type: string
        - in: body
          name: body
          description: Update a transaction category
          required: true
          schema:
            type: object
            properties:
                Category:
                  type: string
                Notes:
                  type: string
      produces:
        - application/json  
      responses:
        '200':
          description: Category updated successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Invalid fields
        '500':
          description: Internal Server Error

  /transactions/{transactionId}/notes:
    put:
      security:
        - Bearer: []
      tags:
        - User transaction notes
      summary: Update notes
      description: Update a transaction notes
      # operationId: updateNotes
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: Attach Id transaction
          required: true
          type: string
        - in: body
          name: body
          description: Update a transaction notes
          required: true
          schema:
            type: object
            properties:
                Category:
                  type: string
                Notes:
                  type: string
      produces:
        - application/json  
      responses:
        '200':
          description: Notes updated successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '404':
          description: Invalid fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:

  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name

  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  UserAccounts:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          account:
            type: object
            properties:
              title:
                type: string
              balance:
                type: integer
              description:
                type: string

  Transactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transaction:
            type: object
            properties:
              date:
                type: string
              description:
                type: string
              amount:
                type: integer
              transactionType:
                type: string
              category:
                type: string
              notes:
                type: string
