export const promiseChat_title = "You are our #1 priority"
export const promiseChat_text = "Need to talk to a representative? You can get in touch through our 24/7 chat or through a phone call in less than 5 minutes."
export const promiseMoney_title = "More savings means higher rates"
export const promiseMoney_text = "The more you save with us, the higher your interest rate will be!"
export const promiseSecurity_title = "Security you can trust"
export const promiseSecurity_text = "We use top of the line encryption to make sure your data and money is always safe"